### ISSUE TITLE
acode-plugin-prettier has a typo in the app

### ISSUE THREAD

**Issue by Ghost10TheYer** [deadlyjack/acode-plugin-prettier#14]
![Screenshot_20230801-124239](https://github.com/deadlyjack/acode-plugin-prettier/assets/102638157/6ae8d012-b8c2-4eb9-8e2d-d0f885244196)

As you can see in the screenshot above, the plugin header is __acode-plugin-perttier__ instead of __acode-plugin-prettier__, It's not originating from the readme file in the plugin repo because I double-checked and It's all okay.

I've just updated Acode, could it be the cause of why I'm seeing this?

**Comment by deadlyjack** [comment]
Thanks, I've fixed it.
